# Generated by Django 5.0.6 on 2024-07-25 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('dni_alumno', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('colegio_procedencia', models.CharField(blank=True, max_length=100, null=True)),
                ('es_nuevo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('genero', models.CharField(blank=True, max_length=10, null=True)),
                ('dni_apoderado', models.CharField(max_length=20, unique=True)),
                ('parentesco', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=9, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('profesion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentacionAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificado_estudios', models.FileField(upload_to='documentacion/')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('nivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grados', to='app.nivel')),
            ],
        ),
    ]
